# Generated by Django 5.1.6 on 2025-03-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_file_chatmessage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='file',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='image',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(default='Default message'),
            preserve_default=False,
        ),
    ]
