# Generated by Django 5.1.6 on 2025-03-31 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chatmessage_file_remove_chatmessage_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp']},
        ),
    ]
