# Generated by Django 5.1.6 on 2025-03-31 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_status'),
        ('chat', '0004_alter_chatmessage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.booking'),
        ),
    ]
