# Generated by Django 5.1.6 on 2025-03-31 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_status'),
        ('chat', '0005_alter_chatmessage_options_chatmessage_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='booking',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='bookings.booking'),
            preserve_default=False,
        ),
    ]
